media:
  input: public
  output: /
content:
  - name: recipes
    label: Recipes
    type: collection
    path: src/content/blog
    filename: "{slug}"
    view:
      fields: [title, category, cookTime]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: category, label: Category, type: string, required: true }
      - { name: image, label: Image, type: image }
      - { name: cookTime, label: Cook Time, type: string }
      - { name: prepTime, label: Prep Time, type: string }
      - { name: servings, label: Servings, type: number, required: true }
      - { name: tags, label: Tags, type: string, list: true }
      - name: ingredients
        label: Ingredients
        type: object
        list: true
        fields:
          - { name: name, label: Name, type: string, required: true }
          - { name: quantity, label: Quantity, type: number, required: true }
          - { name: unit, label: Unit, type: string }
      - { name: body, label: Instructions, type: rich-text }
